from io import BytesIO
from typing import List, Tuple, Dict
from langchain_core.documents import Document
from langchain_core.messages import BaseMessage
from pydantic import BaseModel, Field, ConfigDict

from cat.services.memory.messages import CatMessage


class AgentInput(BaseModel):
    """
    Represents the input to an agent including context documents, user input, and chat history.

    Attributes
    ----------
    context: List[Document]
        List of context documents relevant to the agent's task.
    input: str
        The user's input message to the agent.
    history: List[BaseMessage], optional
        The chat history as a list of messages, by default [].
    """
    context: List[Document]
    input: str
    history: List[BaseMessage] = Field(default_factory=list)


class AgentOutput(BaseModel):
    """
    Represents the output from an agent execution including text and actions.

    Attributes
    ----------
    output: str | None, optional
        The textual output generated by the agent, by default None.
    intermediate_steps: List, optional
        Intermediate steps taken during the agent's execution, by default None.
    with_llm_error: bool, optional
        Indicates if there was an error during LLM processing, by default False.
    """
    output: str | None = None
    intermediate_steps: List[Tuple[Tuple[str | None, Dict, Dict] | None, str]] = Field(default_factory=list)
    with_llm_error: bool = False


class StoredFileWithMetadata(BaseModel):
    """
    Represents a stored file along with its metadata.

    Attributes
    ----------
    name: str
        The unique identifier of the stored file.
    content: BytesIO
        The content of the file as a BytesIO stream.
    metadata: Dict
        A dictionary containing metadata associated with the file.
    """
    name: str
    content: BytesIO
    metadata: Dict

    model_config = ConfigDict(arbitrary_types_allowed=True)


class ChatResponse(BaseModel):
    agent_id: str
    user_id: str
    chat_id: str
    message: CatMessage


# Empty class to represent the basic plugin Settings model
class PluginSettingsModel(BaseModel):
    pass


class PluginManifest(BaseModel):
    id: str
    name: str = "Unknown"
    version: str = "0.0.0"
    thumb: str = None
    tags: str = "Unknown"
    description: str = (
        "Description not found for this plugin. Please create a plugin.json manifest in the plugin folder."
    )
    author_name: str = "Unknown"
    author_url: str = "Unknown"
    plugin_url: str = "Unknown"
    min_cat_version: str = None
    max_cat_version: str = "Unknown"
    local_info: Dict = Field(default_factory=dict)
    dependencies: List[str] = Field(default_factory=list)