from typing import List, Tuple, Dict

from langchain_core.documents import Document
from langchain_core.messages import BaseMessage
from pydantic import BaseModel, Field


class AgentInput(BaseModel):
    """
    Represents the input to an agent including context documents, user input, and chat history.

    Attributes
    ----------
    context: List[Document]
        List of context documents relevant to the agent's task.
    input: str
        The user's input message to the agent.
    history: List[BaseMessage], optional
        The chat history as a list of messages, by default [].
    """
    context: List[Document]
    input: str
    history: List[BaseMessage] = Field(default_factory=list)


class AgentOutput(BaseModel):
    """
    Represents the output from an agent execution including text and actions.

    Attributes
    ----------
    output: str | None, optional
        The textual output generated by the agent, by default None.
    intermediate_steps: List, optional
        Intermediate steps taken during the agent's execution, by default None.
    with_llm_error: bool, optional
        Indicates if there was an error during LLM processing, by default False.
    """
    output: str | None = None
    intermediate_steps: List[Tuple[Tuple[str | None, Dict, Dict] | None, str]] = Field(default_factory=list)
    with_llm_error: bool = False
